### ISSUE TITLE
Clarification about whether to use for or while loop to solve problem

### ISSUE THREAD

**Issue by ShubSharma123** [learn-co-curriculum/dsc-while-loops-break-and-continue-lab#3]
## Link to Canvas

https://learning.flatironschool.com/courses/7380/assignments/258639?module_item_id=613172

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [**X**] Instructions unclear
- [ ] Other (explain below)

### Source

```
**Heading: For Loops
Markdown instructions: Use a while loop to create two lists below of...
Comment instructions: Use a for or while loop to feed the hungry patrons who have an even number...**
```

### Concern

**The above markdown is causing an issue, because I am not sure whether to use a for or while loop to solve the problem.**

## (Optional) Proposed Solution

**Clarify whether to use a for or while loop.**

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [**X**] Saturn Cloud from Canvas

## Any Additional Context?

**None, thank you!**

**Comment by bpurdy-ds** [comment]
Thank you for bringing this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
Removed the word "while" in the first quoted statement.
